<?xml version="1.0" encoding="UTF-8"?>
<Project id="SYL_413" name="TestSG" userID="SYL" flexoID="413" dontEscapeLatex="false">
  <FlexoStorageResource id="SYL_COMPONENT_LIBRARY.TestSG" className="org.openflexo.foundation.rm.FlexoComponentLibraryResource" file="TestSG.wolib" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,16:06:43 20/12/2011 066" userID="SYL" />
  <FlexoStorageResource id="SYL_DATA_MODEL.TestSG" className="org.openflexo.foundation.rm.FlexoDMResource" file="DataModel/TestSG.dm" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,16:06:43 20/12/2011 044" userID="SYL" />
  <FlexoStorageResource id="SYL_DOMAIN_KEY_VALUE.TestSG" className="org.openflexo.foundation.rm.FlexoDKVResource" file="DomainKeyValue/TestSG.dkv" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,16:06:43 20/12/2011 049" userID="SYL" />
  <FlexoStorageResource id="SYL_EOMODEL.EOPrototypes.eomodeld" className="org.openflexo.foundation.rm.FlexoEOModelResource" file="DataModel/EOPrototypes.eomodeld" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,14:18:08 20/12/2011 383" userID="SYL" />
  <FlexoStorageResource id="SYL_EOMODEL.FlexoExecutionModel.eomodeld" className="org.openflexo.foundation.rm.FlexoEOModelResource" file="DataModel/FlexoExecutionModel.eomodeld" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,14:18:08 20/12/2011 388" userID="SYL" />
  <FlexoStorageResource id="SYL_GENERATED_CODE.TestSG" className="org.openflexo.foundation.rm.GeneratedCodeResource" file="GeneratedCode/TestSG.cg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,16:06:43 20/12/2011 054" userID="SYL" />
  <FlexoStorageResource id="SYL_GENERATED_DOC.TestSG" className="org.openflexo.foundation.rm.GeneratedDocResource" file="Documentation/TestSG.dg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,16:06:43 20/12/2011 045" userID="SYL" />
  <FlexoStorageResource id="SYL_GENERATED_SOURCES.TestSG" className="org.openflexo.foundation.rm.GeneratedSourcesResource" file="GeneratedSources/TestSG.sg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,16:06:43 20/12/2011 055" userID="SYL" />
  <FlexoStorageResource id="SYL_IMPLEMENTATION_MODEL.DefaultImplementationModel" className="org.openflexo.foundation.rm.ImplementationModelResource" file="GeneratedSources/DefaultImplementationModel/DefaultImplementationModel.im" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,01:00:00 01/01/1970 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliConfigServiceAPI.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliConfigServiceAPI.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,14:18:04 20/12/2011 600" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliCore.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliCore.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,14:18:04 20/12/2011 605" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliDBBusinessLogic.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliDBBusinessLogic.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,14:18:04 20/12/2011 606" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliExceptionServiceAPI.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliExceptionServiceAPI.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,14:18:04 20/12/2011 607" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliFileMimeTypeServiceAPI.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliFileMimeTypeServiceAPI.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,14:18:08 20/12/2011 375" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliLanguageServiceAPI.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliLanguageServiceAPI.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,14:18:04 20/12/2011 608" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliLocalizationServiceAPI.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliLocalizationServiceAPI.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,14:18:08 20/12/2011 376" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliMailServiceAPI.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliMailServiceAPI.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,14:18:04 20/12/2011 610" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliResourcesAPI.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliResourcesAPI.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,14:18:04 20/12/2011 611" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliRoleServiceAPI.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliRoleServiceAPI.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,14:18:04 20/12/2011 612" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliServiceManager.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliServiceManager.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,14:18:04 20/12/2011 612" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliUserInCookieServiceAPI.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliUserInCookieServiceAPI.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,14:18:08 20/12/2011 379" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliUserServiceAPI.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliUserServiceAPI.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,14:18:08 20/12/2011 380" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.JavaEOControl.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/JavaEOControl.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,14:18:04 20/12/2011 622" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.JavaFoundation.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/JavaFoundation.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,14:18:04 20/12/2011 634" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.JavaWebObjects.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/JavaWebObjects.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,14:18:04 20/12/2011 640" userID="SYL" />
  <FlexoStorageResource id="SYL_NAVIGATION_MENU.TestSG" className="org.openflexo.foundation.rm.FlexoNavigationMenuResource" file="TestSG.menu" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,16:06:43 20/12/2011 057" userID="SYL" />
  <FlexoProcessResource id="SYL_PROCESS.TestSG" name="TestSG" file="Workflow/TestSG.xml" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,16:06:43 20/12/2011 070" userID="SYL" />
  <FlexoStorageResource id="SYL_RM.TestSG" className="org.openflexo.foundation.rm.FlexoRMResource" file="TestSG.rmxml" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,16:06:43 20/12/2011 189" userID="SYL" />
  <TOCResource id="SYL_TOC_RESOURCE.TestSG" userID="SYL" file="Documentation/TestSG.toc" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,16:06:43 20/12/2011 047" />
  <FlexoWebServerFileResource id="SYL_WEBSERVER.001-Dialog.jpg" userID="SYL" file="ImportedImages/001-Dialog.jpg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,14:18:08 20/12/2011 405" />
  <FlexoWebServerFileResource id="SYL_WEBSERVER.002-Information.jpg" userID="SYL" file="ImportedImages/002-Information.jpg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,14:18:08 20/12/2011 406" />
  <FlexoWebServerFileResource id="SYL_WEBSERVER.003-FillForm.jpg" userID="SYL" file="ImportedImages/003-FillForm.jpg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,14:18:08 20/12/2011 407" />
  <FlexoWebServerFileResource id="SYL_WEBSERVER.004-InformationComputer.jpg" userID="SYL" file="ImportedImages/004-InformationComputer.jpg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,14:18:08 20/12/2011 408" />
  <FlexoWebServerFileResource id="SYL_WEBSERVER.005-AssemblyLine.jpg" userID="SYL" file="ImportedImages/005-AssemblyLine.jpg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,14:18:08 20/12/2011 409" />
  <FlexoWebServerFileResource id="SYL_WEBSERVER.006-FlexoServerVideo.jpg" userID="SYL" file="ImportedImages/006-FlexoServerVideo.jpg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,14:18:08 20/12/2011 409" />
  <FlexoWebServerFileResource id="SYL_WEBSERVER.007-Audio.jpg" userID="SYL" file="ImportedImages/007-Audio.jpg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,14:18:08 20/12/2011 410" />
  <FlexoWebServerFileResource id="SYL_WEBSERVER.agileMapping.jpg" userID="SYL" file="ImportedImages/agileMapping.jpg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,14:18:08 20/12/2011 411" />
  <FlexoWebServerFileResource id="SYL_WEBSERVER.objective-process.jpg" userID="SYL" file="ImportedImages/objective-process.jpg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,14:18:08 20/12/2011 412" />
  <FlexoWebServerFileResource id="SYL_WEBSERVER.organisationStructure.jpg" userID="SYL" file="ImportedImages/organisationStructure.jpg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,14:18:08 20/12/2011 413" />
  <FlexoWebServerFileResource id="SYL_WEBSERVER.process-mapping.jpg" userID="SYL" file="ImportedImages/process-mapping.jpg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,14:18:08 20/12/2011 414" />
  <FlexoStorageResource id="SYL_WORKFLOW.TestSG" className="org.openflexo.foundation.rm.FlexoWorkflowResource" file="Workflow/TestSG.wkf" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,16:06:43 20/12/2011 068" userID="SYL" />
</Project>

