/*
 * (c) Copyright 2010-2011 AgileBirds
 *
 * This file is part of OpenFlexo.
 *
 * OpenFlexo is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * OpenFlexo is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OpenFlexo. If not, see <http://www.gnu.org/licenses/>.
 *
 */
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.11.26 at 12:29:16 PM CET 
//
package org.oasis_open.docs.wsbpel._2_0.plnktype;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the org.oasis_open.docs.wsbpel._2_0.plnktype package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {
    private final static QName _PartnerLinkType_QNAME = new QName("http://docs.oasis-open.org/wsbpel/2.0/plnktype",
            "partnerLinkType");
    private final static QName _Role_QNAME = new QName("http://docs.oasis-open.org/wsbpel/2.0/plnktype",
            "role");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.oasis_open.docs.wsbpel._2_0.plnktype
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TExtensibleElements }
     *
     */
    public TExtensibleElements createTExtensibleElements() {
        return new TExtensibleElements();
    }

    /**
     * Create an instance of {@link TRole }
     *
     */
    public TRole createTRole() {
        return new TRole();
    }

    /**
     * Create an instance of {@link Documentation }
     *
     */
    public Documentation createDocumentation() {
        return new Documentation();
    }

    /**
     * Create an instance of {@link TPartnerLinkType }
     *
     */
    public TPartnerLinkType createTPartnerLinkType() {
        return new TPartnerLinkType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPartnerLinkType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/wsbpel/2.0/plnktype", name = "partnerLinkType")
    public JAXBElement<TPartnerLinkType> createPartnerLinkType(
        TPartnerLinkType value) {
        return new JAXBElement<TPartnerLinkType>(_PartnerLinkType_QNAME,
            TPartnerLinkType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRole }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/wsbpel/2.0/plnktype", name = "role")
    public JAXBElement<TRole> createRole(TRole value) {
        return new JAXBElement<TRole>(_Role_QNAME, TRole.class, null, value);
    }
}
