/**
 * Metaphase Editor - WYSIWYG HTML Editor Component
 * Copyright (C) 2010  Rudolf Visagie
 * Full text of license can be found in com/metaphaseeditor/LICENSE.txt
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * The author can be contacted at metaphase.editor@gmail.com.
 */

package com.metaphaseeditor;

/**
 * 
 * @author Rudolf Visagie
 */
public class EmailLinkPanel extends javax.swing.JPanel {

	/** Creates new form EmailLinkPanel */
	public EmailLinkPanel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
	 * method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		emailAddressLabel = new javax.swing.JLabel();
		messageSubjectLabel = new javax.swing.JLabel();
		messageBodyLabel = new javax.swing.JLabel();
		messageSubjectTextField = new javax.swing.JTextField();
		emailAddressTextField = new javax.swing.JTextField();
		jScrollPane1 = new javax.swing.JScrollPane();
		messageBodyTextArea = new javax.swing.JTextArea();

		emailAddressLabel.setText("E-mail Address");

		messageSubjectLabel.setText("Message Subject");

		messageBodyLabel.setText("Message Body");

		messageBodyTextArea.setColumns(20);
		messageBodyTextArea.setRows(5);
		jScrollPane1.setViewportView(messageBodyTextArea);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
												.addComponent(messageBodyLabel, javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														javax.swing.GroupLayout.Alignment.LEADING,
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(messageSubjectLabel)
																				.addComponent(emailAddressLabel))
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(emailAddressTextField,
																						javax.swing.GroupLayout.DEFAULT_SIZE, 289,
																						Short.MAX_VALUE)
																				.addComponent(messageSubjectTextField,
																						javax.swing.GroupLayout.DEFAULT_SIZE, 289,
																						Short.MAX_VALUE)))).addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(
								layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(emailAddressLabel)
										.addComponent(emailAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(
								layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(messageSubjectLabel)
										.addComponent(messageSubjectTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(messageBodyLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE).addContainerGap()));
	}// </editor-fold>//GEN-END:initComponents

	public String getEmailAddress() {
		return emailAddressTextField.getText();
	}

	public String getMessageSubject() {
		return messageSubjectTextField.getText();
	}

	public String getMessageBody() {
		return messageBodyTextArea.getText();
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel emailAddressLabel;
	private javax.swing.JTextField emailAddressTextField;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel messageBodyLabel;
	private javax.swing.JTextArea messageBodyTextArea;
	private javax.swing.JLabel messageSubjectLabel;
	private javax.swing.JTextField messageSubjectTextField;
	// End of variables declaration//GEN-END:variables

}
