<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="market"
    nsURI="http://www.itemis.de/showcases/cdo/market/0.0.1">
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Market" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actors" upperBound="-1"
        eType="#//Actor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="articles" upperBound="-1"
        eType="#//Article" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actor" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sells" upperBound="-1"
        eType="#//Article" eOpposite="#//Article/isSoldBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="buys" upperBound="-1" eType="#//Article"
        eOpposite="#//Article/isBoughtBy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Article" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="isSoldBy" eType="#//Actor"
        eOpposite="#//Actor/sells"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isBoughtBy" eType="#//Actor"
        eOpposite="#//Actor/buys"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
</ecore:EPackage>