<?xml version="1.0" encoding="UTF-8"?>
<Project id="SYL_413" name="TestVE" userID="SYL" flexoID="413" dontEscapeLatex="false">
  <FlexoStorageResource id="SYL_COMPONENT_LIBRARY.TestVE" className="org.openflexo.foundation.rm.FlexoComponentLibraryResource" lastKnownMemoryUpdate="HH:mm:ss dd/MM/yyyy SSS,12:47:07 03/04/2012 000" file="TestVE.wolib" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,12:47:07 03/04/2012 000" userID="SYL" />
  <FlexoStorageResource id="SYL_DATA_MODEL.TestVE" className="org.openflexo.foundation.rm.FlexoDMResource" lastKnownMemoryUpdate="HH:mm:ss dd/MM/yyyy SSS,13:19:37 03/04/2012 379" file="DataModel/TestVE.dm" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,13:19:54 03/04/2012 145" userID="SYL" />
  <FlexoStorageResource id="SYL_DOMAIN_KEY_VALUE.TestVE" className="org.openflexo.foundation.rm.FlexoDKVResource" lastKnownMemoryUpdate="HH:mm:ss dd/MM/yyyy SSS,12:47:07 03/04/2012 000" file="DomainKeyValue/TestVE.dkv" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,12:47:07 03/04/2012 000" userID="SYL" />
  <FlexoStorageResource id="SYL_EOMODEL.EOPrototypes.eomodeld" className="org.openflexo.foundation.rm.FlexoEOModelResource" lastKnownMemoryUpdate="HH:mm:ss dd/MM/yyyy SSS,10:46:00 04/10/2011 000" file="DataModel/EOPrototypes.eomodeld" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,10:46:00 04/10/2011 000" userID="SYL" />
  <FlexoStorageResource id="SYL_EOMODEL.FlexoExecutionModel.eomodeld" className="org.openflexo.foundation.rm.FlexoEOModelResource" lastKnownMemoryUpdate="HH:mm:ss dd/MM/yyyy SSS,10:46:00 04/10/2011 000" file="DataModel/FlexoExecutionModel.eomodeld" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,10:46:00 04/10/2011 000" userID="SYL" />
  <FlexoStorageResource id="SYL_EOMODEL.sdffdsfsd.eomodeld" className="org.openflexo.foundation.rm.FlexoEOModelResource" lastKnownMemoryUpdate="HH:mm:ss dd/MM/yyyy SSS,13:19:37 03/04/2012 379" file="DataModel/sdffdsfsd.eomodeld" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,13:19:54 03/04/2012 051" userID="SYL" />
  <FlexoStorageResource id="SYL_GENERATED_CODE.TestVE" className="org.openflexo.foundation.rm.GeneratedCodeResource" lastKnownMemoryUpdate="HH:mm:ss dd/MM/yyyy SSS,12:47:07 03/04/2012 000" file="GeneratedCode/TestVE.cg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,12:47:07 03/04/2012 000" userID="SYL" />
  <FlexoStorageResource id="SYL_GENERATED_DOC.TestVE" className="org.openflexo.foundation.rm.GeneratedDocResource" file="Documentation/TestVE.dg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,12:47:07 03/04/2012 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliConfigServiceAPI.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliConfigServiceAPI.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,10:46:00 04/10/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliCore.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliCore.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,10:46:00 04/10/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliDBBusinessLogic.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliDBBusinessLogic.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,10:46:00 04/10/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliExceptionServiceAPI.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliExceptionServiceAPI.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,10:46:00 04/10/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliFileMimeTypeServiceAPI.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliFileMimeTypeServiceAPI.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,10:46:00 04/10/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliLanguageServiceAPI.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliLanguageServiceAPI.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,10:46:00 04/10/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliLocalizationServiceAPI.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliLocalizationServiceAPI.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,10:46:00 04/10/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliMailServiceAPI.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliMailServiceAPI.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,10:46:00 04/10/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliResourcesAPI.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliResourcesAPI.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,10:46:00 04/10/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliRoleServiceAPI.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliRoleServiceAPI.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,10:46:00 04/10/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliServiceManager.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliServiceManager.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,10:46:00 04/10/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliUserInCookieServiceAPI.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliUserInCookieServiceAPI.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,10:46:00 04/10/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliUserServiceAPI.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliUserServiceAPI.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,10:46:00 04/10/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.JavaEOControl.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/JavaEOControl.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,10:45:59 04/10/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.JavaFoundation.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/JavaFoundation.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,10:45:58 04/10/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.JavaWebObjects.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/JavaWebObjects.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,10:45:59 04/10/2011 000" userID="SYL" />
  <FlexoStorageResource id="SYL_NAVIGATION_MENU.TestVE" className="org.openflexo.foundation.rm.FlexoNavigationMenuResource" lastKnownMemoryUpdate="HH:mm:ss dd/MM/yyyy SSS,12:47:07 03/04/2012 000" file="TestVE.menu" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,12:47:07 03/04/2012 000" userID="SYL" />
  <FlexoProcessResource id="SYL_PROCESS.TestVE" name="TestVE" file="Workflow/TestVE.xml" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,12:47:07 03/04/2012 000" userID="SYL" lastKnownMemoryUpdate="HH:mm:ss dd/MM/yyyy SSS,12:47:07 03/04/2012 000" />
  <FlexoStorageResource id="SYL_PROJECT_ONTOLOGY.TestVE" className="org.openflexo.foundation.rm.FlexoProjectOntologyResource" lastKnownMemoryUpdate="HH:mm:ss dd/MM/yyyy SSS,13:17:05 03/04/2012 502" file="Ontology/TestVE.owl" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,13:17:13 03/04/2012 878" userID="SYL" />
  <FlexoStorageResource id="SYL_RM.TestVE" className="org.openflexo.foundation.rm.FlexoRMResource" lastKnownMemoryUpdate="HH:mm:ss dd/MM/yyyy SSS,13:18:13 03/04/2012 378" file="TestVE.rmxml" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,13:19:54 03/04/2012 163" userID="SYL" />
  <Shema id="SYL_SHEMA.BasicOrganization" name="BasicOrganization" file="Ontology/BasicOrganization.shema" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,13:16:39 03/04/2012 348" userID="SYL" lastKnownMemoryUpdate="HH:mm:ss dd/MM/yyyy SSS,12:47:32 03/04/2012 604" />
  <Shema id="SYL_SHEMA.R&amp;DDefinition" name="R&amp;DDefinition" file="Ontology/R&amp;DDefinition.shema" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,13:17:13 03/04/2012 910" userID="SYL" lastKnownMemoryUpdate="HH:mm:ss dd/MM/yyyy SSS,13:17:05 03/04/2012 543" />
  <Shema id="SYL_SHEMA.TestOrganizationMap" name="TestOrganizationMap" file="Ontology/TestOrganizationMap.shema" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,13:16:39 03/04/2012 377" userID="SYL" lastKnownMemoryUpdate="HH:mm:ss dd/MM/yyyy SSS,13:16:31 03/04/2012 861" />
  <FlexoStorageResource id="SYL_SHEMA_LIBRARY.TestVE" className="org.openflexo.foundation.rm.FlexoOEShemaLibraryResource" lastKnownMemoryUpdate="HH:mm:ss dd/MM/yyyy SSS,13:17:36 03/04/2012 217" file="Ontology/TestVE.oelib" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,13:17:42 03/04/2012 288" userID="SYL" />
  <TOCResource id="SYL_TOC_RESOURCE.TestVE" userID="SYL" lastKnownMemoryUpdate="HH:mm:ss dd/MM/yyyy SSS,12:47:07 03/04/2012 000" file="Documentation/TestVE.toc" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,12:47:07 03/04/2012 000" />
  <FlexoWebServerFileResource id="SYL_WEBSERVER.001-Dialog.jpg" userID="SYL" file="ImportedImages/001-Dialog.jpg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,10:46:01 04/10/2011 000" />
  <FlexoWebServerFileResource id="SYL_WEBSERVER.002-Information.jpg" userID="SYL" file="ImportedImages/002-Information.jpg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,10:46:01 04/10/2011 000" />
  <FlexoWebServerFileResource id="SYL_WEBSERVER.003-FillForm.jpg" userID="SYL" file="ImportedImages/003-FillForm.jpg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,10:46:01 04/10/2011 000" />
  <FlexoWebServerFileResource id="SYL_WEBSERVER.004-InformationComputer.jpg" userID="SYL" file="ImportedImages/004-InformationComputer.jpg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,10:46:01 04/10/2011 000" />
  <FlexoWebServerFileResource id="SYL_WEBSERVER.005-AssemblyLine.jpg" userID="SYL" file="ImportedImages/005-AssemblyLine.jpg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,10:46:01 04/10/2011 000" />
  <FlexoWebServerFileResource id="SYL_WEBSERVER.006-FlexoServerVideo.jpg" userID="SYL" file="ImportedImages/006-FlexoServerVideo.jpg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,10:46:01 04/10/2011 000" />
  <FlexoWebServerFileResource id="SYL_WEBSERVER.007-Audio.jpg" userID="SYL" file="ImportedImages/007-Audio.jpg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,10:46:01 04/10/2011 000" />
  <FlexoWebServerFileResource id="SYL_WEBSERVER.agileMapping.jpg" userID="SYL" file="ImportedImages/agileMapping.jpg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,10:46:01 04/10/2011 000" />
  <FlexoWebServerFileResource id="SYL_WEBSERVER.objective-process.jpg" userID="SYL" file="ImportedImages/objective-process.jpg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,10:46:01 04/10/2011 000" />
  <FlexoWebServerFileResource id="SYL_WEBSERVER.organisationStructure.jpg" userID="SYL" file="ImportedImages/organisationStructure.jpg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,10:46:01 04/10/2011 000" />
  <FlexoWebServerFileResource id="SYL_WEBSERVER.process-mapping.jpg" userID="SYL" file="ImportedImages/process-mapping.jpg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,10:46:01 04/10/2011 000" />
  <FlexoStorageResource id="SYL_WORKFLOW.TestVE" className="org.openflexo.foundation.rm.FlexoWorkflowResource" lastKnownMemoryUpdate="HH:mm:ss dd/MM/yyyy SSS,12:47:07 03/04/2012 000" file="Workflow/TestVE.wkf" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,12:47:07 03/04/2012 000" userID="SYL" />
  <FlexoStorageResource id="SYL_WS_LIBRARY.TestVE" className="org.openflexo.foundation.rm.FlexoWSLibraryResource" lastKnownMemoryUpdate="HH:mm:ss dd/MM/yyyy SSS,12:47:07 03/04/2012 000" file="WebService/TestVE.ws" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,12:47:07 03/04/2012 000" userID="SYL" />
</Project>

