<?xml version="1.0" encoding="UTF-8"?>
<Project id="SYL_413" name="TestVE" userID="SYL" flexoID="413" dontEscapeLatex="false">
  <FlexoStorageResource id="SYL_COMPONENT_LIBRARY.TestVE" className="org.openflexo.foundation.rm.FlexoComponentLibraryResource" file="TestVE.wolib" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,18:19:12 22/12/2011 000" userID="SYL" />
  <FlexoStorageResource id="SYL_DATA_MODEL.TestVE" className="org.openflexo.foundation.rm.FlexoDMResource" file="DataModel/TestVE.dm" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,18:19:12 22/12/2011 000" userID="SYL" />
  <FlexoStorageResource id="SYL_DOMAIN_KEY_VALUE.TestVE" className="org.openflexo.foundation.rm.FlexoDKVResource" file="DomainKeyValue/TestVE.dkv" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,18:19:12 22/12/2011 000" userID="SYL" />
  <FlexoStorageResource id="SYL_EOMODEL.EOPrototypes.eomodeld" className="org.openflexo.foundation.rm.FlexoEOModelResource" file="DataModel/EOPrototypes.eomodeld" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,11:16:28 15/11/2011 000" userID="SYL" />
  <FlexoStorageResource id="SYL_EOMODEL.FlexoExecutionModel.eomodeld" className="org.openflexo.foundation.rm.FlexoEOModelResource" file="DataModel/FlexoExecutionModel.eomodeld" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,11:16:47 15/11/2011 000" userID="SYL" />
  <FlexoStorageResource id="SYL_GENERATED_CODE.TestVE" className="org.openflexo.foundation.rm.GeneratedCodeResource" file="GeneratedCode/TestVE.cg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,18:19:12 22/12/2011 000" userID="SYL" />
  <FlexoStorageResource id="SYL_GENERATED_DOC.TestVE" className="org.openflexo.foundation.rm.GeneratedDocResource" file="Documentation/TestVE.dg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,18:19:12 22/12/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliConfigServiceAPI.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliConfigServiceAPI.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,11:16:40 15/11/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliCore.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliCore.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,11:15:42 15/11/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliDBBusinessLogic.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliDBBusinessLogic.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,11:15:40 15/11/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliExceptionServiceAPI.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliExceptionServiceAPI.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,11:15:49 15/11/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliFileMimeTypeServiceAPI.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliFileMimeTypeServiceAPI.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,11:15:45 15/11/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliLanguageServiceAPI.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliLanguageServiceAPI.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,11:16:20 15/11/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliLocalizationServiceAPI.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliLocalizationServiceAPI.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,11:15:37 15/11/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliMailServiceAPI.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliMailServiceAPI.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,11:16:16 15/11/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliResourcesAPI.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliResourcesAPI.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,11:15:39 15/11/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliRoleServiceAPI.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliRoleServiceAPI.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,11:16:22 15/11/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliServiceManager.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliServiceManager.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,11:16:37 15/11/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliUserInCookieServiceAPI.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliUserInCookieServiceAPI.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,11:16:37 15/11/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliUserServiceAPI.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliUserServiceAPI.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,11:16:14 15/11/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.JavaEOControl.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/JavaEOControl.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,11:16:05 15/11/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.JavaFoundation.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/JavaFoundation.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,11:15:50 15/11/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.JavaWebObjects.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/JavaWebObjects.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,11:15:58 15/11/2011 000" userID="SYL" />
  <FlexoStorageResource id="SYL_NAVIGATION_MENU.TestVE" className="org.openflexo.foundation.rm.FlexoNavigationMenuResource" file="TestVE.menu" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,18:19:12 22/12/2011 000" userID="SYL" />
  <FlexoProcessResource id="SYL_PROCESS.TestVE" name="TestVE" file="Workflow/TestVE.xml" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,18:19:12 22/12/2011 000" userID="SYL" />
  <FlexoStorageResource id="SYL_PROJECT_ONTOLOGY.TestVE" className="org.openflexo.foundation.rm.FlexoProjectOntologyResource" file="Ontology/TestVE.owl" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,18:19:12 22/12/2011 000" userID="SYL" />
  <FlexoStorageResource id="SYL_RM.TestVE" className="org.openflexo.foundation.rm.FlexoRMResource" file="TestVE.rmxml" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,18:19:12 22/12/2011 000" userID="SYL" />
  <Shema id="SYL_SHEMA.BasicOrganization" name="BasicOrganization" file="Ontology/BasicOrganization.shema" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,11:15:38 15/11/2011 000" userID="SYL" />
  <FlexoStorageResource id="SYL_SHEMA_LIBRARY.TestVE" className="org.openflexo.foundation.rm.FlexoOEShemaLibraryResource" file="Ontology/TestVE.oelib" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,18:19:12 22/12/2011 000" userID="SYL" />
  <TOCResource id="SYL_TOC_RESOURCE.TestVE" userID="SYL" file="Documentation/TestVE.toc" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,18:19:12 22/12/2011 000" />
  <FlexoWebServerFileResource id="SYL_WEBSERVER.001-Dialog.jpg" userID="SYL" file="ImportedImages/001-Dialog.jpg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,11:16:17 15/11/2011 000" />
  <FlexoWebServerFileResource id="SYL_WEBSERVER.002-Information.jpg" userID="SYL" file="ImportedImages/002-Information.jpg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,11:15:37 15/11/2011 000" />
  <FlexoWebServerFileResource id="SYL_WEBSERVER.003-FillForm.jpg" userID="SYL" file="ImportedImages/003-FillForm.jpg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,11:16:34 15/11/2011 000" />
  <FlexoWebServerFileResource id="SYL_WEBSERVER.004-InformationComputer.jpg" userID="SYL" file="ImportedImages/004-InformationComputer.jpg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,11:15:53 15/11/2011 000" />
  <FlexoWebServerFileResource id="SYL_WEBSERVER.005-AssemblyLine.jpg" userID="SYL" file="ImportedImages/005-AssemblyLine.jpg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,11:16:26 15/11/2011 000" />
  <FlexoWebServerFileResource id="SYL_WEBSERVER.006-FlexoServerVideo.jpg" userID="SYL" file="ImportedImages/006-FlexoServerVideo.jpg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,11:15:48 15/11/2011 000" />
  <FlexoWebServerFileResource id="SYL_WEBSERVER.007-Audio.jpg" userID="SYL" file="ImportedImages/007-Audio.jpg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,11:15:51 15/11/2011 000" />
  <FlexoWebServerFileResource id="SYL_WEBSERVER.agileMapping.jpg" userID="SYL" file="ImportedImages/agileMapping.jpg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,11:16:21 15/11/2011 000" />
  <FlexoWebServerFileResource id="SYL_WEBSERVER.objective-process.jpg" userID="SYL" file="ImportedImages/objective-process.jpg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,11:15:37 15/11/2011 000" />
  <FlexoWebServerFileResource id="SYL_WEBSERVER.organisationStructure.jpg" userID="SYL" file="ImportedImages/organisationStructure.jpg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,11:15:38 15/11/2011 000" />
  <FlexoWebServerFileResource id="SYL_WEBSERVER.process-mapping.jpg" userID="SYL" file="ImportedImages/process-mapping.jpg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,11:15:54 15/11/2011 000" />
  <FlexoStorageResource id="SYL_WORKFLOW.TestVE" className="org.openflexo.foundation.rm.FlexoWorkflowResource" file="Workflow/TestVE.wkf" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,18:19:12 22/12/2011 000" userID="SYL" />
  <FlexoStorageResource id="SYL_WS_LIBRARY.TestVE" className="org.openflexo.foundation.rm.FlexoWSLibraryResource" file="WebService/TestVE.ws" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,18:19:12 22/12/2011 000" userID="SYL" />
</Project>

