/*
 * (c) Copyright 2010-2011 AgileBirds
 *
 * This file is part of OpenFlexo.
 *
 * OpenFlexo is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * OpenFlexo is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OpenFlexo. If not, see <http://www.gnu.org/licenses/>.
 *
 */
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.11.06 at 03:26:51 PM CET 
//

package org.xmlsoap.schemas.ws._2004._03.business_process;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 * XSD Authors: The child element onAlarm needs to be a Local Element Declaration, because there is another onAlarm element defined for
 * event handlers.
 * 
 * 
 * <p>
 * Java class for tPick complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tPick">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.xmlsoap.org/ws/2004/03/business-process/}tActivity">
 *       &lt;sequence>
 *         &lt;element ref="{http://schemas.xmlsoap.org/ws/2004/03/business-process/}onMessage" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="onAlarm" type="{http://schemas.xmlsoap.org/ws/2004/03/business-process/}tOnAlarmPick" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="createInstance" type="{http://schemas.xmlsoap.org/ws/2004/03/business-process/}tBoolean" default="no" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tPick", propOrder = { "onMessage", "onAlarm" })
public class TPick extends TActivity {

	protected List<TOnMessage> onMessage;
	protected List<TOnAlarmPick> onAlarm;
	@XmlAttribute(namespace = "http://schemas.xmlsoap.org/ws/2004/03/business-process/")
	protected TBoolean createInstance;

	/**
	 * Gets the value of the onMessage property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list
	 * will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the onMessage property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getOnMessage().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link TOnMessage }
	 * 
	 * 
	 */
	public List<TOnMessage> getOnMessage() {
		if (onMessage == null) {
			onMessage = new ArrayList<TOnMessage>();
		}
		return this.onMessage;
	}

	/**
	 * Gets the value of the onAlarm property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list
	 * will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the onAlarm property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getOnAlarm().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link TOnAlarmPick }
	 * 
	 * 
	 */
	public List<TOnAlarmPick> getOnAlarm() {
		if (onAlarm == null) {
			onAlarm = new ArrayList<TOnAlarmPick>();
		}
		return this.onAlarm;
	}

	/**
	 * Gets the value of the createInstance property.
	 * 
	 * @return possible object is {@link TBoolean }
	 * 
	 */
	public TBoolean getCreateInstance() {
		if (createInstance == null) {
			return TBoolean.NO;
		} else {
			return createInstance;
		}
	}

	/**
	 * Sets the value of the createInstance property.
	 * 
	 * @param value
	 *            allowed object is {@link TBoolean }
	 * 
	 */
	public void setCreateInstance(TBoolean value) {
		this.createInstance = value;
	}

}
