<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="emftechnoadaptor"
    nsURI="http://emftechnoadaptor/1.0" nsPrefix="emftechnoadaptor">
  <eClassifiers xsi:type="ecore:EClass" name="EMFModelSlot" eSuperTypes="Foundation.ecore#//FlexoOntologyModelSlot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="technoAdaptor" eType="#//EMFTechnologyAdapter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EMFTechnologyAdapter" eSuperTypes="Foundation.ecore#//TechnologyAdapter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindingFactory" eType="#//EMFBindingFactory"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextManager" eType="#//EMFTechnologyContextAdapter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="create" eType="#//EMFModelRepository"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="create" eType="#//EMFModelSlot"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EMFTechnologyContextAdapter" eSuperTypes="Foundation.ecore#//TechnologyContextManager"/>
  <eClassifiers xsi:type="ecore:EClass" name="EMFAdapterController" eSuperTypes="Foundation.ecore#//TechnologyAdapterControler"/>
  <eClassifiers xsi:type="ecore:EClass" name="EMFMetamodel" eSuperTypes="Foundation.ecore#//FlexoMetamodel"/>
  <eClassifiers xsi:type="ecore:EClass" name="EMFModel" eSuperTypes="Foundation.ecore#//FlexoModel"/>
  <eClassifiers xsi:type="ecore:EClass" name="EMFObjectIndividualPatternRole" eSuperTypes="Foundation.ecore#//IndividualPatternRole"/>
  <eClassifiers xsi:type="ecore:EClass" name="EMFBindingFactory" eSuperTypes="Foundation.ecore#//TechnologyAdapterBindingFactory"/>
  <eClassifiers xsi:type="ecore:EClass" name="AddEMFObjectIndividual" eSuperTypes="Foundation.ecore#//AddIndividual"/>
  <eClassifiers xsi:type="ecore:EClass" name="SelectEMFObjectIndividual" eSuperTypes="Foundation.ecore#//SelectIndividual"/>
  <eClassifiers xsi:type="ecore:EClass" name="EMFModelRepository" eSuperTypes="Foundation.ecore#//ModelRepository">
    <eStructuralFeatures xsi:type="ecore:EReference" name="technoAdapter" eType="#//EMFTechnologyAdapter"/>
  </eClassifiers>
</ecore:EPackage>
