<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="fmlinfrastructure"
    nsURI="http://fmlinfrastructure/1.0" nsPrefix="fmlinfrastructure">
  <eClassifiers xsi:type="ecore:EClass" name="ViewPoint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="" upperBound="-1" eType="#//VirtualModel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VirtualModel" eSuperTypes="#//FlexoConcept">
    <eStructuralFeatures xsi:type="ecore:EReference" name="" upperBound="-1" eType="#//FlexoConcept"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="" upperBound="-1" eType="#//ModelSlot"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FlexoConcept">
    <eStructuralFeatures xsi:type="ecore:EReference" name="" upperBound="-1" eType="#//ConceptRole"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="" upperBound="-1" eType="#//EditionScheme"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelSlot" abstract="true" eSuperTypes="#//ConceptRole">
    <eStructuralFeatures xsi:type="ecore:EReference" name="" lowerBound="1" eType="#//TechnologyAdapter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConceptRole" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TechnologyAdapter" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EditionScheme" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="" upperBound="-1" eType="#//EditionAction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EditionAction" abstract="true"/>
  <eSubpackages name="EPackage0"/>
  <eSubpackages name="EMFConnector">
    <eClassifiers xsi:type="ecore:EClass" name="EMFTechnologyAdapter" eSuperTypes="#//TechnologyAdapter"/>
    <eClassifiers xsi:type="ecore:EClass" name="EMFModelSlot" eSuperTypes="#//ModelSlot"/>
    <eClassifiers xsi:type="ecore:EClass" name="EMFObjectIndividualPatternRole" eSuperTypes="#//ConceptRole"/>
    <eClassifiers xsi:type="ecore:EClass" name="AddEMFObjectIndividual" eSuperTypes="#//EditionAction"/>
    <eClassifiers xsi:type="ecore:EClass" name="RemoveEMFObjectIndividual" eSuperTypes="#//EditionAction"/>
  </eSubpackages>
</ecore:EPackage>
