<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="foundation"
    nsURI="http://foundation/1.0" nsPrefix="foundation">
  <eClassifiers xsi:type="ecore:EClass" name="EditionPatternObject" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EditionPattern" eSuperTypes="#//EditionPatternObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="patternRoles" upperBound="-1"
        eType="#//PatternRole" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childs" upperBound="-1"
        eType="#//EditionPattern"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contraints" upperBound="-1"
        eType="#//EditionPatternConstraint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindingModel" eType="#//BindingModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="virtualModel" eType="#//VirtualModel"
        eOpposite="#//VirtualModel/editionPatterns"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="editionSchemes" upperBound="-1"
        eType="#//EditionScheme" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="behavior" lowerBound="1"
        eType="#//EditionPatternBehavioralFacet" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="structure" eType="#//EditionPatternStructuralFacet"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VirtualModel" eSuperTypes="#//EditionPattern">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelSlots" upperBound="-1"
        eType="#//ModelSlot" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="syncScheme" eType="#//SynchronizationScheme"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="viewpoint" eType="#//Viewpoint"
        eOpposite="#//Viewpoint/virtualModels"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="editionPatterns" upperBound="-1"
        eType="#//EditionPattern" eOpposite="#//EditionPattern/virtualModel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EditionSchemeObject" abstract="true"
      eSuperTypes="#//EditionPatternObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="editionPattern" lowerBound="1"
        eType="#//EditionPattern"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EditionScheme" abstract="true" eSuperTypes="#//EditionSchemeObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//EditionSchemeParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//EditionAction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractActionScheme" abstract="true"
      eSuperTypes="#//EditionScheme"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractCreationScheme" abstract="true"
      eSuperTypes="#//EditionScheme"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActionScheme" eSuperTypes="#//AbstractActionScheme"/>
  <eClassifiers xsi:type="ecore:EClass" name="DeletionScheme" eSuperTypes="#//AbstractActionScheme"/>
  <eClassifiers xsi:type="ecore:EClass" name="SynchronizationScheme" eSuperTypes="#//AbstractActionScheme"/>
  <eClassifiers xsi:type="ecore:EClass" name="CloningScheme" eSuperTypes="#//AbstractCreationScheme"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreationScheme" eSuperTypes="#//AbstractCreationScheme"/>
  <eClassifiers xsi:type="ecore:EClass" name="EditionSchemeParameter" eSuperTypes="#//EditionSchemeObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="CheckBoxParameter" eSuperTypes="#//EditionSchemeParameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="DropDownParameter" eSuperTypes="#//EditionSchemeParameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="FlexoObjectParameter" eSuperTypes="#//EditionSchemeParameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="FloatParameter" eSuperTypes="#//EditionSchemeParameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="ListParameter" eSuperTypes="#//EditionSchemeParameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="InnerModelSlotParameter" eSuperTypes="#//EditionSchemeParameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyParameter" eSuperTypes="#//InnerModelSlotParameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="UriParameter" eSuperTypes="#//InnerModelSlotParameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerParameter" eSuperTypes="#//EditionSchemeParameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="TextAreaParameter" eSuperTypes="#//EditionSchemeParameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="TextFieldParameter" eSuperTypes="#//EditionSchemeParameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="EditionAction" abstract="true" eSuperTypes="#//EditionSchemeObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelSlot" eType="#//ModelSlot"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssignableAction" abstract="true" eSuperTypes="#//EditionAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="DeclarePatternRole" eSuperTypes="#//AssignableAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="AssignationAction" eSuperTypes="#//AssignableAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="PatternRole" eSuperTypes="#//EditionPatternObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelSlot" eType="#//ModelSlot"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitivePatternRole" eSuperTypes="#//PatternRole"/>
  <eClassifiers xsi:type="ecore:EClass" name="EditionPatternConstraint" eSuperTypes="#//EditionPatternObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="BindingModel" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindingVariables" upperBound="-1"
        eType="#//BindingVariable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BindingVariable"/>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentBindingVariable" eSuperTypes="#//BindingVariable"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModelSlot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="adapter" eType="#//TechnologyAdapter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OntologicObjectPatternRole" eSuperTypes="#//PatternRole"/>
  <eClassifiers xsi:type="ecore:EClass" name="IndividualPatternRole" eSuperTypes="#//OntologicObjectPatternRole"/>
  <eClassifiers xsi:type="ecore:EClass" name="TechnologyAdapter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelslot" eType="#//ModelSlot"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EMFTechnologyAdaptor" eSuperTypes="#//TechnologyAdapter"/>
  <eClassifiers xsi:type="ecore:EClass" name="FlexoOntologyModelSlot" eSuperTypes="#//ModelSlot"/>
  <eClassifiers xsi:type="ecore:EClass" name="Viewpoint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="virtualModels" upperBound="-1"
        eType="#//VirtualModel" eOpposite="#//VirtualModel/viewpoint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FetchRequest" abstract="true" eSuperTypes="#//AssignableAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="DeleteAction" eSuperTypes="#//EditionAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="AddIndividual" abstract="true" eSuperTypes="#//AddConcept"/>
  <eClassifiers xsi:type="ecore:EClass" name="AddConcept" abstract="true" eSuperTypes="#//AssignableAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="CloneIndividual" abstract="true" eSuperTypes="#//AddIndividual"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessBindingVariable" eSuperTypes="#//BindingVariable"/>
  <eClassifiers xsi:type="ecore:EClass" name="BindingValue" eSuperTypes="#//AbstractBinding"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractBinding" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EditionPatternInstanceBindingVariable"
      eSuperTypes="#//BindingVariable"/>
  <eClassifiers xsi:type="ecore:EClass" name="PatternRoleBindingVariable" eSuperTypes="#//BindingVariable"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataBinding"/>
  <eClassifiers xsi:type="ecore:EClass" name="EditionPatternBehavioralFacet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="editionPatternSchemes"
        upperBound="-1" eType="#//EditionScheme"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EditionPatternStructuralFacet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="editionPatternPatternRoles"
        upperBound="-1" eType="#//PatternRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddClass" abstract="true" eSuperTypes="#//AddConcept"/>
  <eClassifiers xsi:type="ecore:EClass" name="AddEditionPatternInstance" eSuperTypes="#//AssignableAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClassParameter" eSuperTypes="#//InnerModelSlotParameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClassPatternRole" abstract="true" eSuperTypes="#//OntologicObjectPatternRole"/>
  <eClassifiers xsi:type="ecore:EClass" name="ControlStructureAction" abstract="true"
      eSuperTypes="#//EditionAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionalAction" eSuperTypes="#//ControlStructureAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractAssertion" abstract="true" eSuperTypes="#//EditionSchemeObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataPropertyAssertion" eSuperTypes="#//AbstractAssertion"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataPropertyParameter" eSuperTypes="#//PropertyParameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="SelectEditionPatternInstance" eSuperTypes="#//FetchRequest"/>
  <eClassifiers xsi:type="ecore:EClass" name="SelectIndividual" abstract="true" eSuperTypes="#//FetchRequest"/>
  <eClassifiers xsi:type="ecore:EClass" name="MatchEditionPatternInstance" eSuperTypes="#//AssignableAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="NavigationScheme" eSuperTypes="#//AbstractActionScheme #//DiagramEditionScheme"/>
  <eClassifiers xsi:type="ecore:EClass" name="LinkScheme" eSuperTypes="#//AbstractCreationScheme #//DiagramEditionScheme"/>
  <eClassifiers xsi:type="ecore:EClass" name="DropScheme" eSuperTypes="#//AbstractCreationScheme #//DiagramEditionScheme"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiagramEditionScheme" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionAction" eSuperTypes="#//AssignableAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="FetchRequestIteractionAction" eSuperTypes="#//ControlStructureAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="IterationAction" eSuperTypes="#//ControlStructureAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="TechnologyContextManager"/>
  <eClassifiers xsi:type="ecore:EClass" name="TechnologyAdapterControler"/>
  <eClassifiers xsi:type="ecore:EClass" name="TechnologyAdapterBindingFactory"/>
  <eClassifiers xsi:type="ecore:EClass" name="FlexoModel" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="FlexoMetamodel" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModelRepository"/>
</ecore:EPackage>
