<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="layout"
    nsURI="http://layout/1.0" nsPrefix="layout">
  <eClassifiers xsi:type="ecore:EClass" name="GraphicalRepresentation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="layout" eType="#//Layout"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layoutKind" eType="#//LayoutKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="drawable" eType="#//Drawing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameters" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Layout" abstract="true">
    <eOperations name="run">
      <eParameters name="containedShapes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList"/>
      <eParameters name="containedNodes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList"/>
      <eParameters name=""/>
    </eOperations>
    <eOperations name="done"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="areaSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LayoutKind">
    <eLiterals name="AUTO_LAYOUT"/>
    <eLiterals name="NO_LAYOUT" value="1"/>
    <eLiterals name="ON_DEMAND" value="2" literal="ON_DEMAND"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForceDirectedLayout" eSuperTypes="#//Layout"/>
  <eClassifiers xsi:type="ecore:EClass" name="FrunchmanRienard" eSuperTypes="#//ForceDirectedLayout"/>
  <eClassifiers xsi:type="ecore:EClass" name="ShapeGR" eSuperTypes="#//GraphicalRepresentation"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectorGR" eSuperTypes="#//GraphicalRepresentation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//ShapeGR"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//ShapeGR"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DrawingGR" eSuperTypes="#//GraphicalRepresentation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedConnectorGR" upperBound="-1"
        eType="#//ConnectorGR" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedShapeGR" upperBound="-1"
        eType="#//ShapeGR" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameters"/>
  <eClassifiers xsi:type="ecore:EClass" name="Drawing">
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" eType="#//Model"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model"/>
  <eClassifiers xsi:type="ecore:EClass" name="HierachicalLayout" eSuperTypes="#//Layout"/>
</ecore:EPackage>
