<?xml version="1.0" encoding="UTF-8"?>
<Project id="SYL_391" name="TestBrowser" userID="SYL" flexoID="391" dontEscapeLatex="false">
  <FlexoStorageResource id="SYL_COMPONENT_LIBRARY.TestBrowser" className="org.openflexo.foundation.rm.FlexoComponentLibraryResource" file="TestBrowser.wolib" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,17:47:27 23/12/2011 000" userID="SYL" />
  <FlexoStorageResource id="SYL_DATA_MODEL.TestBrowser" className="org.openflexo.foundation.rm.FlexoDMResource" file="DataModel/TestBrowser.dm" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,17:47:27 23/12/2011 000" userID="SYL" />
  <FlexoStorageResource id="SYL_DOMAIN_KEY_VALUE.TestBrowser" className="org.openflexo.foundation.rm.FlexoDKVResource" file="DomainKeyValue/TestBrowser.dkv" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,17:47:27 23/12/2011 000" userID="SYL" />
  <FlexoStorageResource id="SYL_EOMODEL.EOPrototypes.eomodeld" className="org.openflexo.foundation.rm.FlexoEOModelResource" file="DataModel/EOPrototypes.eomodeld" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,18:16:38 15/11/2011 000" userID="SYL" />
  <FlexoStorageResource id="SYL_EOMODEL.FlexoExecutionModel.eomodeld" className="org.openflexo.foundation.rm.FlexoEOModelResource" file="DataModel/FlexoExecutionModel.eomodeld" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,18:16:44 15/11/2011 000" userID="SYL" />
  <FlexoStorageResource id="SYL_GENERATED_CODE.TestBrowser" className="org.openflexo.foundation.rm.GeneratedCodeResource" file="GeneratedCode/TestBrowser.cg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,17:47:27 23/12/2011 000" userID="SYL" />
  <FlexoStorageResource id="SYL_GENERATED_DOC.TestBrowser" className="org.openflexo.foundation.rm.GeneratedDocResource" file="Documentation/TestBrowser.dg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,17:47:27 23/12/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliConfigServiceAPI.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliConfigServiceAPI.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,18:15:51 15/11/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliCore.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliCore.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,18:15:38 15/11/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliDBBusinessLogic.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliDBBusinessLogic.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,18:15:42 15/11/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliExceptionServiceAPI.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliExceptionServiceAPI.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,18:15:40 15/11/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliFileMimeTypeServiceAPI.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliFileMimeTypeServiceAPI.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,18:15:46 15/11/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliLanguageServiceAPI.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliLanguageServiceAPI.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,18:15:45 15/11/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliLocalizationServiceAPI.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliLocalizationServiceAPI.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,18:15:59 15/11/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliMailServiceAPI.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliMailServiceAPI.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,18:15:38 15/11/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliResourcesAPI.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliResourcesAPI.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,18:15:38 15/11/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliRoleServiceAPI.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliRoleServiceAPI.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,18:15:38 15/11/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliServiceManager.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliServiceManager.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,18:16:30 15/11/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliUserInCookieServiceAPI.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliUserInCookieServiceAPI.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,18:15:51 15/11/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.DenaliUserServiceAPI.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/DenaliUserServiceAPI.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,18:15:42 15/11/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.JavaEOControl.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/JavaEOControl.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,18:15:43 15/11/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.JavaFoundation.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/JavaFoundation.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,18:15:47 15/11/2011 000" userID="SYL" />
  <FlexoFileResource id="SYL_JAR.JavaWebObjects.jar" className="org.openflexo.foundation.rm.FlexoJarResource" file="DataModel/JavaWebObjects.jar" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,18:15:41 15/11/2011 000" userID="SYL" />
  <FlexoStorageResource id="SYL_NAVIGATION_MENU.TestBrowser" className="org.openflexo.foundation.rm.FlexoNavigationMenuResource" file="TestBrowser.menu" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,17:47:27 23/12/2011 000" userID="SYL" />
  <FlexoComponentResource id="SYL_OPERATION_COMPONENT.TestComponent" className="org.openflexo.foundation.rm.FlexoOperationComponentResource" name="TestComponent" file="Components/TestComponent.woxml" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,18:15:40 15/11/2011 000" userID="SYL" />
  <FlexoProcessResource id="SYL_PROCESS.TestBrowser" name="TestBrowser" file="Workflow/TestBrowser.xml" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,17:47:27 23/12/2011 000" userID="SYL" />
  <FlexoProcessResource id="SYL_PROCESS.TestSubProcess" name="TestSubProcess" file="Workflow/TestSubProcess.xml" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,17:47:27 23/12/2011 000" userID="SYL" />
  <FlexoProcessResource id="SYL_PROCESS.TestSubProcess2" name="TestSubProcess2" file="Workflow/TestSubProcess2.xml" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,17:47:27 23/12/2011 000" userID="SYL" />
  <FlexoProcessResource id="SYL_PROCESS.TestSubSubProcess" name="TestSubSubProcess" file="Workflow/TestSubSubProcess.xml" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,17:47:27 23/12/2011 000" userID="SYL" />
  <FlexoStorageResource id="SYL_RM.TestBrowser" className="org.openflexo.foundation.rm.FlexoRMResource" file="TestBrowser.rmxml" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,17:47:27 23/12/2011 000" userID="SYL" />
  <TOCResource id="SYL_TOC_RESOURCE.TestBrowser" userID="SYL" file="Documentation/TestBrowser.toc" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,17:47:27 23/12/2011 000" />
  <FlexoWebServerFileResource id="SYL_WEBSERVER.001-Dialog.jpg" userID="SYL" file="ImportedImages/001-Dialog.jpg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,18:15:49 15/11/2011 000" />
  <FlexoWebServerFileResource id="SYL_WEBSERVER.002-Information.jpg" userID="SYL" file="ImportedImages/002-Information.jpg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,18:15:38 15/11/2011 000" />
  <FlexoWebServerFileResource id="SYL_WEBSERVER.003-FillForm.jpg" userID="SYL" file="ImportedImages/003-FillForm.jpg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,18:15:37 15/11/2011 000" />
  <FlexoWebServerFileResource id="SYL_WEBSERVER.004-InformationComputer.jpg" userID="SYL" file="ImportedImages/004-InformationComputer.jpg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,18:16:41 15/11/2011 000" />
  <FlexoWebServerFileResource id="SYL_WEBSERVER.005-AssemblyLine.jpg" userID="SYL" file="ImportedImages/005-AssemblyLine.jpg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,18:16:22 15/11/2011 000" />
  <FlexoWebServerFileResource id="SYL_WEBSERVER.006-FlexoServerVideo.jpg" userID="SYL" file="ImportedImages/006-FlexoServerVideo.jpg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,18:15:39 15/11/2011 000" />
  <FlexoWebServerFileResource id="SYL_WEBSERVER.007-Audio.jpg" userID="SYL" file="ImportedImages/007-Audio.jpg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,18:15:43 15/11/2011 000" />
  <FlexoWebServerFileResource id="SYL_WEBSERVER.agileMapping.jpg" userID="SYL" file="ImportedImages/agileMapping.jpg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,18:16:01 15/11/2011 000" />
  <FlexoWebServerFileResource id="SYL_WEBSERVER.objective-process.jpg" userID="SYL" file="ImportedImages/objective-process.jpg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,18:16:24 15/11/2011 000" />
  <FlexoWebServerFileResource id="SYL_WEBSERVER.organisationStructure.jpg" userID="SYL" file="ImportedImages/organisationStructure.jpg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,18:16:25 15/11/2011 000" />
  <FlexoWebServerFileResource id="SYL_WEBSERVER.process-mapping.jpg" userID="SYL" file="ImportedImages/process-mapping.jpg" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,18:16:17 15/11/2011 000" />
  <FlexoStorageResource id="SYL_WORKFLOW.TestBrowser" className="org.openflexo.foundation.rm.FlexoWorkflowResource" file="Workflow/TestBrowser.wkf" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,17:47:27 23/12/2011 000" userID="SYL" />
  <FlexoStorageResource id="SYL_WS_LIBRARY.TestBrowser" className="org.openflexo.foundation.rm.FlexoWSLibraryResource" file="WebService/TestBrowser.ws" lastWrittenOnDisk="HH:mm:ss dd/MM/yyyy SSS,17:47:27 23/12/2011 000" userID="SYL" />
</Project>

