/*
 * (c) Copyright 2010-2011 AgileBirds
 *
 * This file is part of OpenFlexo.
 *
 * OpenFlexo is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * OpenFlexo is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OpenFlexo. If not, see <http://www.gnu.org/licenses/>.
 *
 */
package org.openflexo.foundation.dm.action;

import java.util.Vector;
import java.util.logging.Logger;

import org.openflexo.foundation.FlexoEditor;
import org.openflexo.foundation.FlexoModelObject;
import org.openflexo.foundation.action.FlexoAction;
import org.openflexo.foundation.action.FlexoActionType;
import org.openflexo.foundation.dm.AutoGeneratedProcessBusinessDataDMEntity;
import org.openflexo.foundation.dm.ProcessBusinessDataRepository;

public class UpdateAutoGeneratedBusinessDataDMEntity
		extends
		FlexoAction<UpdateAutoGeneratedBusinessDataDMEntity, AutoGeneratedProcessBusinessDataDMEntity, AutoGeneratedProcessBusinessDataDMEntity> {

	private static final Logger logger = Logger.getLogger(UpdateAutoGeneratedBusinessDataDMEntity.class.getPackage().getName());

	public static FlexoActionType<UpdateAutoGeneratedBusinessDataDMEntity, AutoGeneratedProcessBusinessDataDMEntity, AutoGeneratedProcessBusinessDataDMEntity> actionType = new FlexoActionType<UpdateAutoGeneratedBusinessDataDMEntity, AutoGeneratedProcessBusinessDataDMEntity, AutoGeneratedProcessBusinessDataDMEntity>(
			"update_business_data", FlexoActionType.defaultGroup, FlexoActionType.NORMAL_ACTION_TYPE) {
		@Override
		public UpdateAutoGeneratedBusinessDataDMEntity makeNewAction(AutoGeneratedProcessBusinessDataDMEntity focusedObject,
				Vector<AutoGeneratedProcessBusinessDataDMEntity> globalSelection, FlexoEditor editor) {
			return new UpdateAutoGeneratedBusinessDataDMEntity(focusedObject, globalSelection, editor);
		}

		@Override
		public boolean isVisibleForSelection(AutoGeneratedProcessBusinessDataDMEntity object,
				Vector<AutoGeneratedProcessBusinessDataDMEntity> globalSelection) {
			return isEnabledForSelection(object, globalSelection);
		}

		@Override
		public boolean isEnabledForSelection(AutoGeneratedProcessBusinessDataDMEntity object,
				Vector<AutoGeneratedProcessBusinessDataDMEntity> globalSelection) {
			return true;
		}
	};

	static {
		FlexoModelObject.addActionForClass(actionType, AutoGeneratedProcessBusinessDataDMEntity.class);
	}

	UpdateAutoGeneratedBusinessDataDMEntity(AutoGeneratedProcessBusinessDataDMEntity focusedObject,
			Vector<AutoGeneratedProcessBusinessDataDMEntity> globalSelection, FlexoEditor editor) {
		super(actionType, focusedObject, globalSelection, editor);
	}

	@Override
	protected void doAction(Object context) {
		logger.info("Generate processes business data");
		((ProcessBusinessDataRepository) getFocusedObject().getRepository()).generateProcessBusinessData(getGlobalSelection());
	}
}
