/*
 * (c) Copyright 2010-2011 AgileBirds
 *
 * This file is part of OpenFlexo.
 *
 * OpenFlexo is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * OpenFlexo is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OpenFlexo. If not, see <http://www.gnu.org/licenses/>.
 *
 */
package org.netbeans.lib.cvsclient.event;

import java.util.EventObject;

/**
 * The base class of all events that are generated by the CVS library. Specialisations of this class give more details about the event.
 * 
 * @author Robert Greig
 */
public abstract class CVSEvent extends EventObject {
	/**
	 * Construct a CVS event.
	 * 
	 * @param source
	 *            the object that is logically the source of the event
	 */
	public CVSEvent(Object source) {
		super(source);
	}

	/**
	 * Fire the event to the event listener. Subclasses should call the appropriate method on the listener to dispatch this event.
	 * 
	 * @param listener
	 *            the event listener
	 */
	protected abstract void fireEvent(CVSListener listener);
}