/*
 * (c) Copyright 2010-2011 AgileBirds
 *
 * This file is part of OpenFlexo.
 *
 * OpenFlexo is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * OpenFlexo is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OpenFlexo. If not, see <http://www.gnu.org/licenses/>.
 *
 */
package org.openflexo.dm.view.controller.action;

import java.util.logging.Logger;

import org.openflexo.dm.view.controller.DMController;
import org.openflexo.dm.view.controller.DMSelectionManager;
import org.openflexo.view.controller.ControllerActionInitializer;


public class DMControllerActionInitializer extends ControllerActionInitializer
{

    protected static final Logger logger = Logger.getLogger(DMControllerActionInitializer.class.getPackage().getName());

    DMController _dmController;

    public DMControllerActionInitializer(DMController controller) 
    {
        super(controller);
        _dmController = controller;
    }

    protected DMSelectionManager getDMSelectionManager()
    {
        return _dmController.getDMSelectionManager();
    }

    protected DMController getDMController()
    {
        return _dmController;
    }

    @Override
	public void initializeActions()
    {
        super.initializeActions();
        
        (new DMSetPropertyInitializer(this)).init();

        (new DMCopyInitializer(this)).init();
        (new DMCutInitializer(this)).init();
        (new DMPasteInitializer(this)).init();
        (new DMDeleteInitializer(this)).init();
        (new DMSelectAllInitializer(this)).init();
        (new CreateDMRepositoryInitializer(this)).init();
        (new CreateDMPackageInitializer(this)).init();
        (new CreateDMEntityInitializer(this)).init();
        (new CreateDMPropertyInitializer(this)).init();
        (new CreateDMMethodInitializer(this)).init();
        (new CreateDMTranstyperInitializer(this)).init();
        (new CreateDMEOModelInitializer(this)).init();
        (new ImportDMEOModelInitializer(this)).init();
        (new CreateDMEOEntityInitializer(this)).init();
        (new CreateDMEOAttributeInitializer(this)).init();
        (new CreateDMEORelationshipInitializer(this)).init();
        (new UpdateDMRepositoryInitializer(this)).init();
        (new ShowTypeHierarchyInitializer(this)).init();
        (new ImportJDKEntityInitializer(this)).init();
        (new UpdateLoadableDMEntityInitializer(this)).init();
        (new DuplicateDMMethodInitializer(this)).init();
        (new CreateComponentFromEntityInitializer(this)).init();
        (new ResetSourceCodeInitializer(this)).init();
        (new CreateERDiagramInitializer(this)).init();
        (new GenerateProcessesBusinessDataDMEntityInitializer(this)).init();
        (new UpdateAutoGeneratedBusinessDataDMEntityInitializer(this)).init();
     }

 
}
