classes.dir = target/classes
src.dir = src/main/java
resources.dir = .
application.name = TSTApplication
project.name = TSTApplication
package.name = TSTApplication
build.version = 0.1.7
tag = FC_0_1_7_20060622
application.conf = Application.conf.TST
webxml.woroot = /home/Apple
webxml.mode = Development
database = Frontbase
wosystem.embed=true
webxml.customcontent = 
