#!/bin/bash
#
# make_dmg
#
# make hfsplus disk image from directory
#
# sudo make_dmg <dir_path> <dmg_name> [volume_label]
#

if [ -z "$SUDO_COMMAND" ]   # Need to run this with sudo 
then 
   mntusr=$(id -u) grpusr=$(id -g) sudo $0 "$@" 
   exit 0 
fi 
if [ -d "$1" ]              # dir_path 
then 
 dir_path=$1
else
  echo "Must pass in valid dir. $1 is not valid" 
  exit 
fi
if [ -n "$2" ]              # dmg_name
then 
 dmg_name=$2
else
  echo "Must pass name for dmg $2 is not valid" 
  exit 
fi
if [ -n "$3" ]              # volume_label. 
then 
 volume_label=$3
else
  volume_label="Untitled"
  echo
  echo "Using volume_label=Untitled" 
  echo
fi
du_output=`du -sk $dir_path 2>&1`
dir_size=`echo $du_output | cut -f1 -d" "`
let dir_size=$dir_size*1024 
let dir_size=$dir_size/1000 
dir_size=`expr $dir_size + 1124` 
dd if=/dev/zero of="$dmg_name" bs=1024 count=$dir_size
/sbin/mkfs.hfsplus -v "$volume_label" "$dmg_name"
timestamp=`date +%Y%m%d.%H%M%S`
mountdir=`mktemp -d flexobuild-$timestamp.XXXXXXXXXX`
echo $mountdir
mount -o loop -t hfsplus "$dmg_name" $mountdir
cp -r $dir_path/* $mountdir
umount $mountdir
rmdir $mountdir
